### ISSUE TITLE
more docs?

### ISSUE THREAD

**Issue by vetal20600** [gamecredits-project/block-exploder#16]
Hello, guys! Nice, beautiful and simple explorer. Well done!
I am not such familiar with py. Do you have any more documentation about deployment and running the production environment?
I am guessing this is not enough readme file only to run production.

**Comment by Vuksan** [comment]
Hello. Thank you very much 😄 
The readme is all you need in order to start our block explorer locally.
We still don't have automatic script for deployment, but we're working on it.

**Comment by vetal20600** [comment]
Can you explain ho they are linked: [block-explorer](github.com/gamecredits-project/block-exploder) and block-explorer-ui ?

**Comment by Vuksan** [comment]
block-explorer-ui is a separate repo for the front-end

**Comment by vetal20600** [comment]
I am considering to apply you sources to get explorer for some POS coin. I hope, you can give a conclusion about this idea. 
Any limitations for POS currency? Any suggestions?
Thanks!

**Comment by vetal20600** [comment]
@Vuksan I am considering about to use you sources to get explorer for some POS coin. I hope, you can give a conclusion about this idea.
Any limitations for POS currency? Any advices? Thanks!

**Comment by Vuksan** [comment]
It shouldn't be a huge difference, but I haven't done it for a POS coin yet, so I can't give any advice.
Good luck!

**Comment by vetal20600** [comment]
Thank you!
I am currently running your explorer. It's awesome!
![screen_shot_2017-12-11](https://user-images.githubusercontent.com/4103746/33810415-cf6f4b4c-de0c-11e7-81c3-116010cde06f.png)

But seems like ui does now work well and I am not sure why

**Comment by Vuksan** [comment]
Sorry, I didn't work on the UI part, I will get someone else to answer it.

**Comment by vetal20600** [comment]
it seems like ui source code is not latest version placed here, but no this is no problem now.
maybe you know why it happens https://github.com/gamecredits-project/block-exploder/issues/17 ?

**Comment by MicicFilip** [comment]
Closing this issue because it has been resolved
